# coding: utf-8

"""
    Woolball AI Network API

    **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.text_generation_api import TextGenerationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTextGenerationApi(unittest.TestCase):
    """TextGenerationApi unit test stubs"""

    def setUp(self):
        self.api = TextGenerationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_text_generation(self):
        """Test case for text_generation

        Text Generation - Multi-Provider  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
