# coding: utf-8

"""
    Woolball AI Network API

    **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.text_generation_response import TextGenerationResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestTextGenerationResponse(unittest.TestCase):
    """TextGenerationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextGenerationResponse(self):
        """Test TextGenerationResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.text_generation_response.TextGenerationResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
