# coding: utf-8

"""
    Woolball AI Network API

    **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.speech_recognition_api import SpeechRecognitionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSpeechRecognitionApi(unittest.TestCase):
    """SpeechRecognitionApi unit test stubs"""

    def setUp(self):
        self.api = SpeechRecognitionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_speech_to_text(self):
        """Test case for speech_to_text

        Speech Recognition (Speech-to-Text)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
