# coding: utf-8

# flake8: noqa
"""
    Woolball AI Network API

    **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.chunk import Chunk
from swagger_client.models.one_of_speech_to_text_request_contract_input import OneOfSpeechToTextRequestContractInput
from swagger_client.models.stt_chunk import STTChunk
from swagger_client.models.speech_to_text_request_contract import SpeechToTextRequestContract
from swagger_client.models.tts_response import TTSResponse
from swagger_client.models.text_generation_request_contract import TextGenerationRequestContract
from swagger_client.models.text_generation_response import TextGenerationResponse
from swagger_client.models.text_to_speech_request_contract import TextToSpeechRequestContract
from swagger_client.models.translation_request_contract import TranslationRequestContract
from swagger_client.models.translation_response import TranslationResponse
