# coding: utf-8

"""
    Woolball AI Network API

    **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class STTChunk(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'text': 'str',
        'chunks': 'list[Chunk]'
    }

    attribute_map = {
        'text': 'text',
        'chunks': 'chunks'
    }

    def __init__(self, text=None, chunks=None):  # noqa: E501
        """STTChunk - a model defined in Swagger"""  # noqa: E501
        self._text = None
        self._chunks = None
        self.discriminator = None
        if text is not None:
            self.text = text
        if chunks is not None:
            self.chunks = chunks

    @property
    def text(self):
        """Gets the text of this STTChunk.  # noqa: E501


        :return: The text of this STTChunk.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this STTChunk.


        :param text: The text of this STTChunk.  # noqa: E501
        :type: str
        """

        self._text = text

    @property
    def chunks(self):
        """Gets the chunks of this STTChunk.  # noqa: E501


        :return: The chunks of this STTChunk.  # noqa: E501
        :rtype: list[Chunk]
        """
        return self._chunks

    @chunks.setter
    def chunks(self, chunks):
        """Sets the chunks of this STTChunk.


        :param chunks: The chunks of this STTChunk.  # noqa: E501
        :type: list[Chunk]
        """

        self._chunks = chunks

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(STTChunk, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, STTChunk):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
