# coding: utf-8

"""
    Woolball AI Network API

    **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TTSResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'audio': 'str',
        'format': 'str',
        'sample_rate': 'int'
    }

    attribute_map = {
        'audio': 'audio',
        'format': 'format',
        'sample_rate': 'sample_rate'
    }

    def __init__(self, audio=None, format=None, sample_rate=None):  # noqa: E501
        """TTSResponse - a model defined in Swagger"""  # noqa: E501
        self._audio = None
        self._format = None
        self._sample_rate = None
        self.discriminator = None
        if audio is not None:
            self.audio = audio
        if format is not None:
            self.format = format
        if sample_rate is not None:
            self.sample_rate = sample_rate

    @property
    def audio(self):
        """Gets the audio of this TTSResponse.  # noqa: E501


        :return: The audio of this TTSResponse.  # noqa: E501
        :rtype: str
        """
        return self._audio

    @audio.setter
    def audio(self, audio):
        """Sets the audio of this TTSResponse.


        :param audio: The audio of this TTSResponse.  # noqa: E501
        :type: str
        """

        self._audio = audio

    @property
    def format(self):
        """Gets the format of this TTSResponse.  # noqa: E501


        :return: The format of this TTSResponse.  # noqa: E501
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format):
        """Sets the format of this TTSResponse.


        :param format: The format of this TTSResponse.  # noqa: E501
        :type: str
        """

        self._format = format

    @property
    def sample_rate(self):
        """Gets the sample_rate of this TTSResponse.  # noqa: E501


        :return: The sample_rate of this TTSResponse.  # noqa: E501
        :rtype: int
        """
        return self._sample_rate

    @sample_rate.setter
    def sample_rate(self, sample_rate):
        """Sets the sample_rate of this TTSResponse.


        :param sample_rate: The sample_rate of this TTSResponse.  # noqa: E501
        :type: int
        """

        self._sample_rate = sample_rate

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TTSResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TTSResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
